Modify styling for listview items
light-launcher/Light-Android-Launcher pull request #58
Opened 2019-03-14 21:02 UTC by taylor-josh

Resolves #42 
Also resolves #31 which sounds like a duplicate Issue of #42
Should also resolve #30 since I had to move the creation of the
left-padding down the actual listview items to get onClick effect to
extend across the whole width of the screen.

2019-03-14 21:03 UTC, taylor-josh commented
![example](https://user-images.githubusercontent.com/39976320/54391376-0cbac800-467b-11e9-8662-2d84c59c077e.gif)

2019-03-14 21:27 UTC, postapczuk requested changes

2019-03-14 21:27 UTC, postapczuk commented on LaLauncher/src/main/java/com/github/postapczuk/lalauncher/AppsActivity.java
> +            TextView selectedItem = view.findViewById(view.getId());
duplicated code - you could extract it to method in AppsActivity, and use it in both places

2019-03-14 21:27 UTC, postapczuk commented on LaLauncher/src/main/java/com/github/postapczuk/lalauncher/MainActivity.java
> +            TextView selectedItem = view.findViewById(view.getId());
Ok, now it's trippled - as I mentioned create method in AppsActivity accessible for all classes that extend it

2019-03-14 21:27 UTC, postapczuk commented on LaLauncher/src/main/java/com/github/postapczuk/lalauncher/AllAppsActivity.java
> +    private void applyItemPadding(TextView item){
duplicated private method (here and in MainActivity). Move it to the AppsActivity with proper access (remove `private` word)

2019-03-15 01:03 UTC, jancborchardt commented
Very very nice @taylor-josh! :) How much opacity is it? It looks like it could be even more transparent as it’s very harsh white / light grey?

2019-03-15 01:56 UTC, taylor-josh commented
Thanks @jancborchardt!

For the highlight effect behind the items when they are clicked? That is
set at 40% opacity. I was attempting to get the colors close to what was
already being used. When I was testing, it didn't seem that harsh to me.
Thoughts, @postapczuk ?

On Thu, Mar 14, 2019, 9:03 PM Jan-Christoph Borchardt <
notifications@github.com> wrote:

> Very very nice @taylor-josh <https://github.com/taylor-josh>! :) How much
> opacity is it? It looks like it could be even more transparent as it’s very
> harsh white / light grey?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/light-launcher/Light-Android-Launcher/pull/58#issuecomment-473121294>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AmH9gAytuYMJ3Iov9v-Fny6LdMpZ-varks5vWvF1gaJpZM4b1NdZ>
> .
>

2019-03-15 05:10 UTC, postapczuk approved these changes

2019-03-15 05:15 UTC, merged

2019-03-15 07:11 UTC, jancborchardt commented
@taylor-josh right, 60% opacity – for the mockup at https://github.com/light-launcher/Light-Android-Launcher/pull/54#issuecomment-472625092 it is 4% opacity for example, and still very visible. :)

What do you think about using something lower like 4%, or 10%?

2019-03-15 15:07 UTC, taylor-josh commented
Yeah, I can always take a look at dropping the opacity some the next time I am in the project working on something.

2019-03-15 22:11 UTC, jancborchardt commented
@taylor-josh or let me know which values I need to modify? :)

2019-03-16 00:40 UTC, taylor-josh commented
The background color should be in the colors.xml file and I believe is
called backgroundBackgroundFavorite. Now that I think about it, that is a
crappy name since it's not only used in the favorite screen.

On Fri, Mar 15, 2019, 6:11 PM Jan-Christoph Borchardt <
notifications@github.com> wrote:

> @taylor-josh <https://github.com/taylor-josh> or let me know which values
> I need to modify? :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/light-launcher/Light-Android-Launcher/pull/58#issuecomment-473457155>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AmH9gM6UhjM5SHUoUp4iMf-1TJCWBko9ks5vXBp0gaJpZM4b1NdZ>
> .
>