Optimised epaper version
light-launcher/Light-Android-Launcher pull request #62
Opened 2019-04-18 06:28 UTC by snug

Updated application name to differentiate version
Removed animations from menu changes
Changed colours to white

This resolves issue #61

2019-04-18 10:40 UTC, jancborchardt commented
This changes the main version though? Isn’t it possible to detect if the screen or device is an e-paper device and automatically adjust?

2019-04-18 10:58 UTC, postapczuk commented
Sadly not.

2019-04-18 16:02 UTC, postapczuk requested changes

2019-04-18 16:02 UTC, postapczuk commented on LaLauncher/src/main/res/anim/slide_down.xml
> -            android:duration="400"
Slides are already removed on the epaper branch from the code, so I'suggest to remove this xml completely

2019-04-18 16:02 UTC, postapczuk commented on LaLauncher/src/main/res/anim/slide_up.xml
> +            android:duration="0"
Same here, xml to remove

2019-04-18 16:08 UTC, postapczuk commented on LaLauncher/src/main/res/values/colors.xml
> +    <color name="colorTransparent">#00FFFFFF</color>
I don't think this change cause anything as first two digits are "00" which is equal transparency=0. I'd leave that as 00000000

2019-10-07 21:08 UTC, closed without merging

2019-10-07 21:09 UTC, postapczuk commented
No one took care to this. Changes were applied on epaper branch.